# Generated by Django 5.1.6 on 2025-02-18 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., Sidebar Top, Below Passage', max_length=100)),
                ('code', models.TextField(help_text='Google AdSense or other ad code')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('exam_type', models.CharField(choices=[('CHSL', 'CHSL Exam'), ('CGL', 'CGL Exam'), ('NTPC', 'NTPC Exam')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=50)),
                ('wpm', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_app.typingpassage')),
            ],
        ),
    ]
