# Generated by Django 5.1.6 on 2025-02-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('CHSL', 'CHSL Exam'), ('CGL', 'CGL Exam'), ('NTPC', 'NTPC Exam')], max_length=10, unique=True)),
                ('instructions', models.TextField(help_text='Detailed instructions for the typing test')),
                ('passage', models.TextField(help_text='Typing passage for the test')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='passage',
        ),
        migrations.AddField(
            model_name='testresult',
            name='exam_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typing_app.examcontent'),
        ),
        migrations.DeleteModel(
            name='TypingPassage',
        ),
    ]
