# Generated by Django 5.1.6 on 2025-02-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_app', '0002_examcontent_remove_testresult_passage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="User's email address", max_length=254)),
                ('suggestion', models.TextField(help_text="User's feedback or suggestion")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
