# Generated by Django 5.1.6 on 2025-02-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_app', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='backspaces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='spaces',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
