# Generated by Django 5.1.6 on 2025-02-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_app', '0004_testresult_backspaces_testresult_spaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CHSL', 'CHSL Exam'), ('CGL', 'CGL Exam'), ('NTPC', 'NTPC Exam')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='examcontent',
            name='exam_type',
        ),
        migrations.AddField(
            model_name='examcontent',
            name='duration',
            field=models.IntegerField(default=10, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='examcontent',
            name='exam_types',
            field=models.ManyToManyField(related_name='exam_contents', to='typing_app.examtype'),
        ),
    ]
