# Generated by Django 5.1.6 on 2025-02-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_app', '0005_examtype_remove_examcontent_exam_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=50)),
                ('game_name', models.CharField(choices=[('speed_typing', 'Speed Typing Challenge'), ('key_hit_trainer', 'Key Hit Trainer'), ('missing_word', 'Type the Missing Word')], max_length=50)),
                ('passage', models.TextField(blank=True, null=True)),
                ('correct_hits', models.PositiveIntegerField(default=0)),
                ('incorrect_hits', models.PositiveIntegerField(default=0)),
                ('wpm', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('time_taken', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(choices=[('CHSL', 'CHSL Exam'), ('CGL', 'CGL Exam'), ('NTPC', 'NTPC Exam'), ('CPCT', 'CPCT Exam')], max_length=10, unique=True),
        ),
    ]
