# Generated by Django 5.1.6 on 2025-02-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_app', '0007_examcontent_passage_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcontent',
            name='passage',
            field=models.TextField(blank=True, help_text='Typing passage for the test'),
        ),
    ]
