# Generated by Django 5.1.6 on 2025-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_app', '0009_alter_examtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(choices=[('CHSL', 'CHSL Exam'), ('CGL', 'CGL Exam'), ('NTPC', 'NTPC Exam'), ('CPCT', 'CPCT Exam'), ('PRACTISE', 'PRACTISE')], max_length=10, unique=True),
        ),
    ]
