# Generated by Django 5.1.6 on 2025-02-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_app', '0010_alter_examtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='actual_key_depressions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='additions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='capitalization',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='full_mistakes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='half_mistakes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='incomplete_words',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='omissions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='punctuation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='repetitions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='spacing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='spelling_errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='substitutions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='time_taken',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_words_typed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
