# Generated by Django 5.1.6 on 2025-02-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_app', '0011_testresult_actual_key_depressions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcontent',
            name='instructions',
        ),
        migrations.AddField(
            model_name='examtype',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for this exam type', null=True),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
