# Generated by Django 5.1.6 on 2025-03-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_app', '0016_blog_delete_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='keywords',
            field=models.CharField(blank=True, max_length=750),
        ),
    ]
