# Generated by Django 5.1.6 on 2025-03-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_app', '0019_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcontent',
            name='passage_french',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examcontent',
            name='passage_german',
            field=models.TextField(blank=True, null=True),
        ),
    ]
